/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de3;

import de1.Form1;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Form3 extends javax.swing.JFrame {

    /**
     * Creates new form Form3
     */
    public Form3() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        svATTT.setSelected(true);
        tfLuong.setEnabled(false);
        tfDonVi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMaSV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        tfNgaySinh = new javax.swing.JTextField();
        tfDiemTB = new javax.swing.JTextField();
        tfHocPhi = new javax.swing.JTextField();
        tfDonVi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfLuong = new javax.swing.JTextField();
        svATTT = new javax.swing.JRadioButton();
        svMM = new javax.swing.JRadioButton();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        saveInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THONG TIN SINH VIEN");

        jLabel2.setText("Loai SV");

        jLabel3.setText("Ma SV");

        jLabel4.setText("Ho ten");

        jLabel5.setText("Ngay sinh");

        jLabel6.setText("Gioi tinh");

        jLabel7.setText("Diem TB");

        jLabel8.setText("Hoc phi");

        jLabel9.setText("Don vi");

        jLabel10.setText("Luong");

        buttonGroup1.add(svATTT);
        svATTT.setText("ATTT");
        svATTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svATTTActionPerformed(evt);
            }
        });

        buttonGroup1.add(svMM);
        svMM.setText("Mat Ma");
        svMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svMMActionPerformed(evt);
            }
        });

        buttonGroup2.add(nam);
        nam.setText("Nam");
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        buttonGroup2.add(nu);
        nu.setText("Nu");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        saveInfo.setText("Luu thong tin");
        saveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(svATTT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(svMM)
                                .addGap(25, 25, 25))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nu)
                                .addGap(45, 45, 45)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(saveInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDiemTB, tfDonVi, tfHoTen, tfHocPhi, tfLuong, tfMaSV, tfNgaySinh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(svATTT)
                    .addComponent(svMM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nam)
                    .addComponent(nu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveInfo)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void svATTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svATTTActionPerformed
        // TODO add your handling code here:
        tfHocPhi.setEnabled(true);
        tfLuong.setEnabled(false);
        tfDonVi.setEnabled(false);
    }//GEN-LAST:event_svATTTActionPerformed

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuActionPerformed

    private void svMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svMMActionPerformed
        // TODO add your handling code here:
        tfHocPhi.setEnabled(false);
        tfLuong.setEnabled(true);
        tfDonVi.setEnabled(true);
    }//GEN-LAST:event_svMMActionPerformed

    private void saveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInfoActionPerformed
        // TODO add your handling code here:
        if(this.checkNull()) {
            JOptionPane.showMessageDialog(null, "Vui long nhap du thong tin");
            return;
        }
        if(svATTT.isSelected()) {
            SinhvienATTT svAttt;
            try {
                svAttt = new SinhvienATTT(tfMaSV.getText(),
                        tfHoTen.getText(),
                        tfNgaySinh.getText(),
                        nam.isSelected() ? "nam" : "nu",
                        Float.parseFloat(tfDiemTB.getText()),
                        Float.parseFloat(tfHocPhi.getText()));
                FileWriter fw = null;
                try {
                    fw = new FileWriter("svat.dat");
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.append("Ma SV: " + svAttt.getMaSV() + "\n" + 
                            "Ho ten: " + svAttt.getHoTen() + "\n" + 
                            "Ngay sinh: " + svAttt.getNgaySinh() + "\n" + 
                            "Gioi tinh: " + svAttt.getGioiTinh() + "\n" +
                            "Diem TB: " + svAttt.getDiemTB() + "\n" + 
                            "Hoc phi: " + svAttt.getHocPhi() + "\n");
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "Luu du lieu thanh cong");
                } catch(Exception ex) {
                    JOptionPane.showMessageDialog(null, "Luu file that bai");
                    Logger.getLogger(Form3.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex);
                return;
            }
        } else {
            SinhvienMatMa svMM;
            try {
                svMM = new SinhvienMatMa(tfMaSV.getText(),
                        tfHoTen.getText(),
                        tfNgaySinh.getText(),
                        nam.isSelected() ? "nam" : "nu",
                        Float.parseFloat(tfDiemTB.getText()),
                        tfDonVi.getText(),
                        Float.parseFloat(tfLuong.getText()));
                FileWriter fw = null;
                try {
                    fw = new FileWriter("svmm.dat");
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.append("Ma SV: " + svMM.getMaSV() + "\n" + 
                            "Ho ten: " + svMM.getHoTen() + "\n" + 
                            "Ngay sinh: " + svMM.getNgaySinh() + "\n" + 
                            "Gioi tinh: " + svMM.getGioiTinh() + "\n" +
                            "Diem TB: " + svMM.getDiemTB() + "\n" + 
                            "Don vi: " + svMM.getDonVi() + "\n" + 
                            "Luong: " + svMM.getLuong());
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "Luu du lieu thanh cong");
                } catch(Exception ex) {
                    JOptionPane.showMessageDialog(null, "Luu file that bai");
                    Logger.getLogger(Form3.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex);
                return;
            }
        }
    }//GEN-LAST:event_saveInfoActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }
    
    public Boolean checkNull() {
        if(tfMaSV.getText().equals("")) return true;
        if(tfHoTen.getText().equals("")) return true;
        if(tfNgaySinh.getText().equals("")) return true;
        if(!nam.isSelected() && !nu.isSelected()) return true;
        if(tfDiemTB.getText().equals("")) return true;
        if(svATTT.isSelected()) {
            if(tfHocPhi.getText().equals("")) return true;
        } else {
            if(tfLuong.getText().equals("")) return true;  
            if(tfDonVi.getText().equals("")) return true;
        }
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JButton saveInfo;
    private javax.swing.JRadioButton svATTT;
    private javax.swing.JRadioButton svMM;
    private javax.swing.JTextField tfDiemTB;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfHocPhi;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMaSV;
    private javax.swing.JTextField tfNgaySinh;
    // End of variables declaration//GEN-END:variables
}
